// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: service/v1/api_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to upload an application metadata
type UploadMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Content of the metadata in yaml format.
	Metadata string `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *UploadMetadataRequest) Reset() {
	*x = UploadMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_api_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadataRequest) ProtoMessage() {}

func (x *UploadMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_api_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadataRequest.ProtoReflect.Descriptor instead.
func (*UploadMetadataRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMetadataRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// Response to upload an application metadata
type UploadMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadMetadataResponse) Reset() {
	*x = UploadMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_api_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadataResponse) ProtoMessage() {}

func (x *UploadMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_api_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadataResponse.ProtoReflect.Descriptor instead.
func (*UploadMetadataResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_api_service_proto_rawDescGZIP(), []int{1}
}

// Request to search application metadata
type SearchMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Content of the query string
	Query string `protobuf:"bytes,10,opt,name=query,proto3" json:"query,omitempty"`
	// for paging
	PageStart string `protobuf:"bytes,20,opt,name=page_start,json=pageStart,proto3" json:"page_start,omitempty"`
	// for paging
	PageSize uint32 `protobuf:"varint,30,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *SearchMetadataRequest) Reset() {
	*x = SearchMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_api_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMetadataRequest) ProtoMessage() {}

func (x *SearchMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_api_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMetadataRequest.ProtoReflect.Descriptor instead.
func (*SearchMetadataRequest) Descriptor() ([]byte, []int) {
	return file_service_v1_api_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMetadataRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMetadataRequest) GetPageStart() string {
	if x != nil {
		return x.PageStart
	}
	return ""
}

func (x *SearchMetadataRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// The record of search result
type MetadataRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the website URL which is used as record key
	Website string `protobuf:"bytes,10,opt,name=website,proto3" json:"website,omitempty"`
	// the metadata content
	Metadata string `protobuf:"bytes,20,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// the last update time
	UpdateTime string `protobuf:"bytes,30,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *MetadataRecord) Reset() {
	*x = MetadataRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_api_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetadataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRecord) ProtoMessage() {}

func (x *MetadataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_api_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRecord.ProtoReflect.Descriptor instead.
func (*MetadataRecord) Descriptor() ([]byte, []int) {
	return file_service_v1_api_service_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataRecord) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *MetadataRecord) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *MetadataRecord) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// Response to search application metadata
type SearchMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// for paging
	NextPageStart string `protobuf:"bytes,10,opt,name=next_page_start,json=nextPageStart,proto3" json:"next_page_start,omitempty"`
	// List of the search result
	Results []*MetadataRecord `protobuf:"bytes,20,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SearchMetadataResponse) Reset() {
	*x = SearchMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_v1_api_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMetadataResponse) ProtoMessage() {}

func (x *SearchMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_api_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMetadataResponse.ProtoReflect.Descriptor instead.
func (*SearchMetadataResponse) Descriptor() ([]byte, []int) {
	return file_service_v1_api_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMetadataResponse) GetNextPageStart() string {
	if x != nil {
		return x.NextPageStart
	}
	return ""
}

func (x *SearchMetadataResponse) GetResults() []*MetadataRecord {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_service_v1_api_service_proto protoreflect.FileDescriptor

var file_service_v1_api_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x61, 0x70, 0x70, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x69, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x1e,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x67,
	0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x40, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70,
	0x70, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0xae, 0x02, 0x0a,
	0x0a, 0x41, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x8c, 0x01, 0x0a, 0x0e,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2d,
	0x2e, 0x61, 0x70, 0x70, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e,
	0x61, 0x70, 0x70, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x3a, 0x01, 0x2a, 0x12, 0x90, 0x01, 0x0a, 0x0e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x2e,
	0x61, 0x70, 0x70, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61,
	0x70, 0x70, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x19, 0x12, 0x17, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x18, 0x5a,
	0x16, 0x61, 0x70, 0x70, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_v1_api_service_proto_rawDescOnce sync.Once
	file_service_v1_api_service_proto_rawDescData = file_service_v1_api_service_proto_rawDesc
)

func file_service_v1_api_service_proto_rawDescGZIP() []byte {
	file_service_v1_api_service_proto_rawDescOnce.Do(func() {
		file_service_v1_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_v1_api_service_proto_rawDescData)
	})
	return file_service_v1_api_service_proto_rawDescData
}

var file_service_v1_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_service_v1_api_service_proto_goTypes = []interface{}{
	(*UploadMetadataRequest)(nil),  // 0: appmeta.api.service.v1.UploadMetadataRequest
	(*UploadMetadataResponse)(nil), // 1: appmeta.api.service.v1.UploadMetadataResponse
	(*SearchMetadataRequest)(nil),  // 2: appmeta.api.service.v1.SearchMetadataRequest
	(*MetadataRecord)(nil),         // 3: appmeta.api.service.v1.MetadataRecord
	(*SearchMetadataResponse)(nil), // 4: appmeta.api.service.v1.SearchMetadataResponse
}
var file_service_v1_api_service_proto_depIdxs = []int32{
	3, // 0: appmeta.api.service.v1.SearchMetadataResponse.results:type_name -> appmeta.api.service.v1.MetadataRecord
	0, // 1: appmeta.api.service.v1.ApiService.UploadMetadata:input_type -> appmeta.api.service.v1.UploadMetadataRequest
	2, // 2: appmeta.api.service.v1.ApiService.SearchMetadata:input_type -> appmeta.api.service.v1.SearchMetadataRequest
	1, // 3: appmeta.api.service.v1.ApiService.UploadMetadata:output_type -> appmeta.api.service.v1.UploadMetadataResponse
	4, // 4: appmeta.api.service.v1.ApiService.SearchMetadata:output_type -> appmeta.api.service.v1.SearchMetadataResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_v1_api_service_proto_init() }
func file_service_v1_api_service_proto_init() {
	if File_service_v1_api_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_v1_api_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_api_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_api_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_api_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetadataRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_v1_api_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_v1_api_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_api_service_proto_goTypes,
		DependencyIndexes: file_service_v1_api_service_proto_depIdxs,
		MessageInfos:      file_service_v1_api_service_proto_msgTypes,
	}.Build()
	File_service_v1_api_service_proto = out.File
	file_service_v1_api_service_proto_rawDesc = nil
	file_service_v1_api_service_proto_goTypes = nil
	file_service_v1_api_service_proto_depIdxs = nil
}
